version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: gatsby
    versions:
    - 2.32.10
    - 2.32.11
    - 2.32.3
    - 2.32.4
    - 2.32.6
    - 2.32.8
    - 2.32.9
  - dependency-name: react-bootstrap
    versions:
    - 1.5.1
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.14.1
    - 2.14.2
  - dependency-name: sass
    versions:
    - 1.32.7
    - 1.32.8
  - dependency-name: gatsby-source-contentful
    versions:
    - 4.6.1
    - 4.6.2
  - dependency-name: socket.io
    versions:
    - 2.4.1
